### ISSUE TITLE
Cannot read property "githubClientId" of undefined

### ISSUE THREAD

**Issue by jhartma** [possibilities/next-github-auth#17]
Logging in and out works great! However, I have a small problem with the ```PrivatePage``` component. When pulling it in, I get
```bash
TypeError: Cannot read property 'githubClientId' of undefined
    at ProvideGithubContextWrapper.getChildContext (.../node_modules/next-github-auth/lib/decorators/ProvideContext.js:57:40)
    at ReactCompositeComponentWrapper._processChildContext (.../node_modules/react-dom/lib/ReactCompositeComponent.js:505:31)
    at ReactCompositeComponentWrapper.performInitialMount (.../node_modules/react-dom/lib/ReactCompositeComponent.js:371:105)
    at ReactCompositeComponentWrapper.mountComponent (.../node_modules/react-dom/lib/ReactCompositeComponent.js:258:21)
    at Object.mountComponent (.../node_modules/react-dom/lib/ReactReconciler.js:46:35)
    at ReactCompositeComponentWrapper.performInitialMount (.../node_modules/react-dom/lib/ReactCompositeComponent.js:371:34)
    at ReactCompositeComponentWrapper.mountComponent (.../node_modules/react-dom/lib/ReactCompositeComponent.js:258:21)
    at Object.mountComponent (.../node_modules/react-dom/lib/ReactReconciler.js:46:35)
    at ReactCompositeComponentWrapper.performInitialMount (.../node_modules/react-dom/lib/ReactCompositeComponent.js:371:34)
    at ReactCompositeComponentWrapper.mountComponent (.../node_modules/react-dom/lib/ReactCompositeComponent.js:258:21)
```

I exported the env variables and the app logs them correctly. Is there anything I am missing?

**Comment by possibilities** [comment]
I'll dig into this ASAP... Any code you can share so I can see how you're
using it?

**Comment by jhartma** [comment]
Thanks for looking into this! Here is the code

```js
// sign-in page
import { SignIn } from "next-github-auth"
export default SignIn

// sign-out page
import { SignOut } from "next-github-auth"
export default SignOut

// Public Page
import { PublicPage, PublicLink, PrivateLink } from "next-github-auth"
import NextLink from "next/link"
const Link = PrivateLink(NextLink)

const IndexPage = () => {
  return (
    <div>
      <div>Welcome</div>
      <Link href="/sources"><a>Private</a></Link>
    </div>
  )
}

export default PublicPage(IndexPage)

// Layout Page for Private Pages
import Head from "next/head"
import { PrivatePage } from "next-github-auth"

export const Layout = PrivatePage(({ children }) => {
  const style = { height: "100%" }

  return (
    <div style={style}>
      <Head>
        <meta charSet="utf-8" />
        <meta content="initial-scale=1.0, width=device-width" name="viewport" />
        <link href="/static/icons.css" rel="stylesheet" />
        <link href="/static/site.css" rel="stylesheet" />
      </Head>
      <div style={style}>
        { children }
      </div>
    </div>
  )
})
```
Without the ```PrivatePage``` wrapper, there is no error, but once it's included I get that error message

**Comment by possibilities** [comment]
The decorators only work on "next pages". So I think the issue here is trying to wrap your layout won't work. The technical reason for this is that the page decorators expect their `getInitialProps` to be invoked (which they in turn invoke on the underlying "wrapped" pages).

**Comment by possibilities** [comment]
I'll hack on the docs a bit to make this all clearer once we hash it out here. Thanks!

**Comment by jhartma** [comment]
Okay thanks, putting it into the next pages works nicely

**Comment by possibilities** [comment]
Nice, I'll keep this open until the docs get some love.

**Comment by possibilities** [comment]
I touched up the README:

https://github.com/possibilities/next-github-auth/commit/7eab11c927454976c4b907cf8adc7332b0a9ed3a#diff-04c6e90faac2675aa89e2176d2eec7d8

And added a check that causes it to error out with a useful explanation if you try to use the decorators on a non-page.

https://github.com/possibilities/next-github-auth/blob/master/src/decorators/PageDecoratorInvariant.js#L20

Peace!
